steps:
  # Step 1: Build the Docker image for the backend
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'  # Specify the backend directory
    args: [
      'build', 
      '-t', 
      'gcr.io/$PROJECT_ID/backend-image:$COMMIT_SHA', 
      '.'
    ]

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'gcr.io/$PROJECT_ID/backend-image:$COMMIT_SHA'
    ]

  # Step 3: Deploy the image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 
      'deploy', 
      'backend',  # Name of your Cloud Run service
      '--image', 
      'gcr.io/$PROJECT_ID/backend-image:$COMMIT_SHA',
      '--region', 
      'europe-west1',  # Specify your region
      '--platform', 
      'managed',
      '--allow-unauthenticated'
    ]

# Define the images to be pushed
images:
  - 'gcr.io/$PROJECT_ID/backend-image:$COMMIT_SHA'